/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_welcome_dialog (void);
GtkWidget* create_find_dialog (void);
GtkWidget* create_ext_window (void);
GtkWidget* create_new_dialog (void);
GtkWidget* create_prefs_dialog (void);
GtkWidget* create_inspector_window (void);
GtkWidget* create_search_window (void);
GtkWidget* create_skein_spacing_dialog (void);
GtkWidget* create_skein_trim_dialog (void);
